apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: asia.gcr.io/poc-innovation-iot/duke-training/user-inquiry
  newTag: v1.4
- name: asia.gcr.io/poc-innovation-iot/duke-user-inquiry-service
  newTag: 02df28e0

  # - behavior: merge
  #   envs:
  #     - configs/config.env
  #   name: user-inquiry-configmap-env
configMapGenerator:
- behavior: merge
  files:
  - configs/config.yaml
  name: user-inquiry-configmap-file

secretGenerator:
- behavior: merge
  envs:
  - secrets/secret.env
  name: user-inquiry-secret-env
  # - behavior: merge
  #   files:
  #     - secrets/secret.yaml
  #   name: user-inquiry-secret-file

patches:
- path: patches/set_resources.yaml
