apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: asia.gcr.io/poc-innovation-iot/duke-training/duke-user-inquiry-service
  newTag: 02df28e0

  # - behavior: merge
  #   envs:
  #     - configs/config.env
  #   name: duke-user-inquiry-service-configmap-env
configMapGenerator:
- behavior: merge
  files:
  - configs/config.yaml
  name: duke-user-inquiry-service-configmap-file

secretGenerator:
- behavior: merge
  envs:
  - secrets/secret.env
  name: duke-user-inquiry-service-secret-env
- behavior: merge
  files:
    - secrets/secret.yaml
  name: duke-user-inquiry-service-secret-file

patches:
- path: patches/set_resources.yaml
