apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: asia.gcr.io/poc-innovation-iot/duke-user-inquiry-service
  newTag: bf430a66
- name: asia.gcr.io/poc-innovation-iot/duke-user-producer-service
  newTag: 830c63bf

configMapGenerator:
- behavior: merge
  files:
  - configs/config.yaml
  name: duke-user-inquiry-service-configmap-file

secretGenerator:
- behavior: merge
  envs:
  - secrets/secret.env
  name: duke-user-inquiry-service-secret-env

patches:
- path: patches/set_resources.yaml
