environment: local

app:
  name: duke-user-inquiry-service

server:
  port: 8080
  timeout: 60

log:
  environment: production 
  level: info
  format: json

postgres:
  host: 172.28.240.42
  port: 5432
  db_name: duke-db

redis:
  address: 172.28.241.3:6379
  database: 1
  authString: 92008bf3-478e-4aaf-9a41-007423d8bfb6

user-list-key: users

