environment: local

app:
  name: duke-user-inquiry-service

server:
  port: 8080
  timeout: 60

log:
  environment: production 
  level: info
  format: json

postgres:
  host: 172.28.240.42
  port: 5432
  db-name: duke-db

redis:
  address: 172.28.241.3:6379
  database: 1

user-list-key: users

