apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-inquiry
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: user-inquiry
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 512Mi
