apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: asia.gcr.io/poc-innovation-iot/duke-training/duke-user-inquiry-service
    newTag: v1.4

configMapGenerator:
  - behavior: merge
    envs:
      - configs/config.env
    name: duke-user-inquiry-service-configmap-env
  - behavior: merge
    files:
      - configs/config.yaml
    name: duke-user-inquiry-service-configmap-file

secretGenerator:
  - behavior: merge
    envs:
      - secrets/secret.env
    name: duke-user-inquiry-service-secret-env

patches:
  - patches/set_resources.yaml
