apiVersion: apps/v1
kind: Deployment
metadata:
  name: duke-user-inquiry-service
  labels:
    app.kubernetes.io/name: duke-user-inquiry-service
    app.kubernetes.io/instance: duke-user-inquiry-service
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: duke-user-inquiry-service
      app.kubernetes.io/instance: duke-user-inquiry-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: duke-user-inquiry-service
        app.kubernetes.io/instance: duke-user-inquiry-service
    spec:
      containers:
        - name: duke-user-inquiry-service
          image: asia.gcr.io/poc-innovation-iot/duke-user-inquiry-service
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: duke-user-inquiry-service-secret-env
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 10
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 10
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 400m
              memory: 256Mi
          volumeMounts:
            - name: duke-user-inquiry-service-configmap-file
              mountPath: app/config/config.yaml
              subPath: config.yaml

      volumes:
        - name: duke-user-inquiry-service-configmap-file
          configMap:
            name: duke-user-inquiry-service-configmap-file
