apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-inquiry
  labels:
    app.kubernetes.io/name: user-inquiry
    app.kubernetes.io/instance: user-inquiry
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: user-inquiry
      app.kubernetes.io/instance: user-inquiry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user-inquiry
        app.kubernetes.io/instance: user-inquiry
    spec:
      containers:
        - name: user-inquiry
          image: asia.gcr.io/poc-innovation-iot/duke-training/duke-user-inquiry-service
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: user-inquiry-configmap-env
            - secretRef:
                name: user-inquiry-secret-env
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 10
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 10
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 400m
              memory: 256Mi
          volumeMounts:
            - name: user-inquiry-configmap-file
              mountPath: /configs/config.yaml
              subPath: config.yaml

      volumes:
        - name: user-inquiry-configmap-file
          configMap:
            name: user-inquiry-configmap-file
